---
# Configuration File
#
#   Components - Components to be loaded at startup
#   Triggers - Event triggers
#   Logging - Specification on what is to be logged during a log dump

#   Set how often components are logged. Default is 300 seconds. 
"log_interval": 10

"soil_sensor":
    "key": "soil_sensor_1"
    "name": "Soil Sensor #1"
    "pin": 0

"gpio_relay":
    "key": "pump_1"
    "name": "Pump #1"
    "pin": "D17"
    "inverted": true
    "maxtime": 5

# Logger Settings
#   format - format to store in, default csv
#   keys - component keys to be logged each cycle
"logger":
    "format": "csv"
    "keys":
        - pump_1
        - soil_sensor_1
